### ISSUE TITLE
Add more examples of array operations

### ISSUE THREAD

**Issue by hugepanda** [IonicaBizau/edit-json-file#25]
Hey, do you mind adding more examples of array operations inside the JSON? Thanks.

**Comment by shimuldn** [comment]
If you still need

"User": [
{
"Country":"US",
"State": "New York"
}
]
}
console.log(file.get("User.0.Country"));
console.log(file.get("User.0.State"));

If you want to access a 2D array, you can do so like.
console.log(file.get("User.0.0.Country"));

**Comment by chakson** [comment]
@shimuldn Hey, how to add a object into the array User by file.set() ? so it would be like:
```
"User": [
{
"Country":"US",
"State": "New York"
},
{
"Country":"US2",
"State": "New York2"
}
]
```
Thanks

**Comment by shimuldn** [comment]
@chakson not sure about array, The best I can help here is bellow examle.

```
file.set(`User.0.Country`, `US`);
file.set(`User.0.State`, `New York`);
file.set(`User.1.Country`, `India`);
file.set(`User.1.State`, `Delhi`);
file.set(`User.2.Country`, `Germany`);
file.set(`User.2.State`, `Berlin`);
```

And the result will be:
```
{
  "User": {
    "0": {
      "Country": "US",
      "State": "New York"
    },
    "1": {
      "Country": "India",
      "State": "Delhi"
    },
    "2": {
      "Country": "Germany",
      "State": "Berlin"
    }
  }
}
```
and you can read like this
`console.log(file.get("User.0.Country"));`

I am not sure how to write arry here but you can convert it by adding []. eg:
```
[
{
  "User": {
    "0": {
      "Country": "US",
      "State": "New York"
    },
    "1": {
      "Country": "India",
      "State": "Delhi"
    },
    "2": {
      "Country": "Germany",
      "State": "Berlin"
    }
  }
}
]
```
Now you can read 
`console.log(file.get("0.User.0.Country"));`

Hope this help.
