### ISSUE TITLE
Need to access data inside a JSON Array.Please provide some examples

### ISSUE THREAD

**Issue by aarthy4f** [IonicaBizau/edit-json-file#26]
"User":  [  
    {
    "Country":"US",
    "SSN": 900000
    }    
    ]    
    }

**Comment by shimuldn** [comment]
Here You go:
console.log(file.get("User.0.Country"));
console.log(file.get("User.0.SSN"));

**Comment by shimuldn** [comment]
> "User": [
> {
> "Country":"US",
> "SSN": 900000
> }
> ]
> }

Here You go:
console.log(file.get("User.0.Country"));
console.log(file.get("User.0.SSN"));
