### ISSUE TITLE
Feature: Option to specify line ending

### ISSUE THREAD

**Issue by nelson6e65** [IonicaBizau/edit-json-file#29]
Wherever to use `CRLF` or `LF`  line ending on writing operations, regardless OS.

**Comment by IonicaBizau** [comment]
This is supported now by using `options.stringify_eol`. Thanks!

**Comment by nelson6e65** [comment]
Thanks. 

In README, states:

> "Wheter to add the new line at the end of the file or not (default: false)".

It now accepts `'CRLF'` and `'LF'` undocumented values, in addition to `true`/`false`?
