### ISSUE TITLE
push to Array feature 

### ISSUE THREAD

**Issue by sungle3737** [IonicaBizau/edit-json-file#30]
how about

```js
let blabla = []
file.set("blabla", blabla)

setInterval(() => {
  blabla.push("ebebe")
  file.set("blabla", blabla)
}, 1000)  
```

to

```js
let blabla = []
file.set("blabla", blabla)

setInterval(() => {
  file.push("blabla", "ebebe")
}, 1000)  
```

for not to rewrite
O(n) -> O(1)

**Comment by IonicaBizau** [comment]
That's a great idea! Contribuitions are welcome. :four_leaf_clover:

**Comment by phcontrols** [comment]
I have installed "edit-json-file": "^1.4.1", I am trying to use file.push(), i get "UncaughtException TypeError: file.push is not a function". May I know ver 1.4.1 supports push method ?

**Comment by sungle3737** [comment]
@phcontrols It is just my suggestion and not real function
