### ISSUE TITLE
Will multiple edit calls to same file from different hosts fail ?

### ISSUE THREAD

**Issue by victormarcus** [IonicaBizau/edit-json-file#34]
Hi
I am exploring your library. There is a single file that can be accessed by multiple users at a time.

let file = editJsonFile("path"); 
file.set("KEY", "VALUE");

How will this library act in this scenario? Is there any provision of lock & wait in this library ?

**Comment by IonicaBizau** [comment]
You will have to handle that. The library does not have any buffer/lock functionality.
