### ISSUE TITLE
Hi, how to change data inside array?

### ISSUE THREAD

**Issue by BronzeCrab** [IonicaBizau/edit-json-file#38]
I.e. we have some json like 
```
{
  "boards": [
    {
      "id": 1,
      "status": "active",
      "date": ""
     }
   ]
}
```
So how can I select first element in array `boards` and set the date there?

**Comment by IonicaBizau** [comment]
I think `set('boards.0.date', "new date")` should work. Otherwise, you can just rewrite the whole array.
