### ISSUE TITLE
Paths that utilize solely integer values results in unexpected behavior.

### ISSUE THREAD

**Issue by cl185208** [IonicaBizau/edit-json-file#56]
If you try to set a path using solely integer values, the second integer value will result in a empty array of that size. 

Example:
`file.set("1.5", {
    "foo": "bar"
})`
Expected:
`{"1": {"5": {"foo": "bar"}}}`
Actual Result:
`{
      "1": [null, null, null, null, null, {"foo": "bar"}
}`

**Comment by IonicaBizau** [comment]
Well, that is actually expected because you are setting the 5th item in the `1` key. To prevent that, simply escape the `.`:

```js
file.set("1\\.5", { ... })
```
